### PR TITLE
Add 0.7.0-beta2

### LINKED ISSUE #20: add support for beta versions
Would it be possible to add support for julia beta versions? Maybe one could introduce a tag `latest-beta` that either takes the latest stable version or, if existent, the superseding beta version.

### PR DESCRIPTION
**Pull request by tianon**
Closes #20

### CODE REVIEW

**Comment by tianon** [comment]
```console
$ ./update.sh
warning: cannot find sha256 for 0.6.4 on arch armv7l / armv7l (armhf); skipping
warning: cannot find sha256 for 0.6.4 on arch aarch64 / aarch64 (arm64); skipping
warning: cannot find sha256 for 0.6.4 on arch ppc64le / ppc64le (ppc64el); skipping
0: 0.6.4
warning: cannot find sha256 for 0.7.0-beta2 on arch aarch64 / aarch64 (arm64); skipping
warning: cannot find sha256 for 0.7.0-beta2 on arch ppc64le / ppc64le (ppc64el); skipping
0-rc: 0.7.0-beta2
```

```diff
$ diff -u <(bashbrew cat julia) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2018-07-24 12:56:39.940260086 -0700
+++ /dev/fd/62	2018-07-24 12:56:39.940260086 -0700
@@ -1,27 +1,47 @@
 Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon), Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
 GitRepo: https://github.com/docker-library/julia.git
 
-Tags: 0.6.3-stretch, 0.6-stretch, 0-stretch, stretch
-SharedTags: 0.6.3, 0.6, 0, latest
-Architectures: amd64, arm32v7, arm64v8, i386
-GitCommit: 3854279e1ffb49d9e34080d476ffdb7c00035455
-Directory: stretch
-
-Tags: 0.6.3-jessie, 0.6-jessie, 0-jessie, jessie
-Architectures: amd64, arm32v7, arm64v8, i386
-GitCommit: 3854279e1ffb49d9e34080d476ffdb7c00035455
-Directory: jessie
+Tags: 0.7.0-beta2-stretch, 0.7.0-stretch, 0.7-stretch, 0-rc-stretch
+SharedTags: 0.7.0-beta2, 0.7.0, 0.7, 0-rc
+Architectures: amd64, arm32v7, i386
+GitCommit: ef1592bb4bad3c9752bfa713f92ec73fa3846d7b
+Directory: 0-rc/stretch
 
-Tags: 0.6.3-windowsservercore-ltsc2016, 0.6-windowsservercore-ltsc2016, 0-windowsservercore-ltsc2016, windowsservercore-ltsc2016
-SharedTags: 0.6.3, 0.6, 0, latest
+Tags: 0.7.0-beta2-windowsservercore-ltsc2016, 0.7.0-windowsservercore-ltsc2016, 0.7-windowsservercore-ltsc2016, 0-rc-windowsservercore-ltsc2016
+SharedTags: 0.7.0-beta2, 0.7.0, 0.7, 0-rc
 Architectures: windows-amd64
-GitCommit: d4f2c502f4604b25de33e6d4e2db23c8d5971c12
-Directory: windows/windowsservercore-ltsc2016
+GitCommit: ef1592bb4bad3c9752bfa713f92ec73fa3846d7b
+Directory: 0-rc/windows/windowsservercore-ltsc2016
 Constraints: windowsservercore-ltsc2016
 
-Tags: 0.6.3-windowsservercore-1709, 0.6-windowsservercore-1709, 0-windowsservercore-1709, windowsservercore-1709
-SharedTags: 0.6.3, 0.6, 0, latest
+Tags: 0.7.0-beta2-windowsservercore-1709, 0.7.0-windowsservercore-1709, 0.7-windowsservercore-1709, 0-rc-windowsservercore-1709
+SharedTags: 0.7.0-beta2, 0.7.0, 0.7, 0-rc
 Architectures: windows-amd64
-GitCommit: d4f2c502f4604b25de33e6d4e2db23c8d5971c12
-Directory: windows/windowsservercore-1709
+GitCommit: ef1592bb4bad3c9752bfa713f92ec73fa3846d7b
+Directory: 0-rc/windows/windowsservercore-1709
+Constraints: windowsservercore-1709
+
+Tags: 0.6.4-stretch, 0.6-stretch, 0-stretch, stretch
+SharedTags: 0.6.4, 0.6, 0, latest
+Architectures: amd64, i386
+GitCommit: ef1592bb4bad3c9752bfa713f92ec73fa3846d7b
+Directory: 0/stretch
+
+Tags: 0.6.4-jessie, 0.6-jessie, 0-jessie, jessie
+Architectures: amd64, i386
+GitCommit: ef1592bb4bad3c9752bfa713f92ec73fa3846d7b
+Directory: 0/jessie
+
+Tags: 0.6.4-windowsservercore-ltsc2016, 0.6-windowsservercore-ltsc2016, 0-windowsservercore-ltsc2016, windowsservercore-ltsc2016
+SharedTags: 0.6.4, 0.6, 0, latest
+Architectures: windows-amd64
+GitCommit: ef1592bb4bad3c9752bfa713f92ec73fa3846d7b
+Directory: 0/windows/windowsservercore-ltsc2016
+Constraints: windowsservercore-ltsc2016
+
+Tags: 0.6.4-windowsservercore-1709, 0.6-windowsservercore-1709, 0-windowsservercore-1709, windowsservercore-1709
+SharedTags: 0.6.4, 0.6, 0, latest
+Architectures: windows-amd64
+GitCommit: ef1592bb4bad3c9752bfa713f92ec73fa3846d7b
+Directory: 0/windows/windowsservercore-1709
 Constraints: windowsservercore-1709
```

**Comment by tianon** [comment]
Gah, `Pkg.add` (which our test runs) has been deprecated in favor of the new `Pkg` package at https://github.com/JuliaLang/julia/tree/v0.7.0-beta2/stdlib/Pkg, and now has unexpected output to stdout that our tests don't account for. :disappointed:

**Comment by tianon** [comment]
@tkelman any simple suggestions? :innocent: (asking since you suggested the addition of `Pkg.add` in our tests back in https://github.com/docker-library/julia/pull/9#issuecomment-249648587)

Our test currently runs the following:

```julia
println("Hello World!");

# https://github.com/docker-library/julia/pull/6
download("https://google.com");

# https://github.com/docker-library/julia/pull/9
Pkg.add("JSON");
```

And expects the output to be `Hello World!` and the exit code to be zero, but perhaps there's a better way?  (Which might involve simply splitting the test into two tests instead.)

**Comment by tkelman** [comment]
Splitting into 2 tests sounds like your easiest option.

(I don't use Julia at all any more, but I don't mind the ping.)

**Comment by tianon** [comment]
> (I don't use Julia at all any more, but I don't mind the ping.)

Ah, that's a shame; thanks for responding anyhow! :heart:

**Pull request merged**
