### PR TITLE
Add Debian Buster variant

### PR DESCRIPTION
**Pull request by J0WI**
Switched to slim variant due https://github.com/docker-library/julia/pull/18#discussion_r187412457

### CODE REVIEW

**Comment by yosifkit** [comment]
:+1:  to buster
Not sure on moving from `stretch` to `stretch-slim`. Since users are likely to be `FROM julia:x-stretch`, it seems possible that we could break their builds.

**Comment by J0WI** [comment]
Should I remove the `-slim` for both or just for `stretch`?

**Comment by tianon** [comment]
Just for stretch

**Comment by J0WI** [comment]
Done

**Pull request merged**
