### PR TITLE
Add Alpine-based Julia 1.5 image

### PR DESCRIPTION
**Pull request by lungben**
The new musl Linux binaries for Julia 1.5 allow a rather simple creation of an Alpine Linux based Julia image.
The size of this image is 380 MB, compared to 456 MB for the Debian based one.

I manually created the Dockerfile for now, integration into the automatic Dockerfile update script is still open.

### CODE REVIEW

**Comment by tianon** [comment]
Neat! Thanks for taking a first pass! :pray:

I've pushed fb8e276 which adds the appropriate template and updates the associated scripts, so this should now be running the image tests via GitHub Actions. :+1: :partying_face: 

<details>
<summary>Diff:</summary>

```diff
$ diff -u <(bashbrew cat julia) <(bashbrew cat <(./generate-stackbrew-library.sh))
--- /dev/fd/63	2020-06-30 12:10:06.179184241 -0700
+++ /dev/fd/62	2020-06-30 12:10:06.179184241 -0700
@@ -7,6 +7,10 @@
 GitCommit: 6a716f3d1f28aaafce298c33e27a053443eec6fb
 Directory: 1.5-rc/buster
 
+Tags: 1.5.0-rc1-alpine3.12, 1.5.0-alpine3.12, 1.5-alpine3.12, 1.5-rc-alpine3.12, rc-alpine3.12, 1.5.0-rc1-alpine, 1.5.0-alpine, 1.5-alpine, 1.5-rc-alpine, rc-alpine
+GitCommit: fb8e27612702b2dc93f109947a4df0f99477f3b0
+Directory: 1.5-rc/alpine3.12
+
 Tags: 1.5.0-rc1-windowsservercore-ltsc2016, 1.5.0-windowsservercore-ltsc2016, 1.5-windowsservercore-ltsc2016, 1.5-rc-windowsservercore-ltsc2016, rc-windowsservercore-ltsc2016
 SharedTags: 1.5.0-rc1, 1.5.0, 1.5, 1.5-rc, rc
 Architectures: windows-amd64
```

</details>

**Comment by lungben** [comment]
Thank you for the integration!

**Comment by fredrikekre** [comment]
I will just note that Julia on musl has known problems and is therefore listed as Tier 3: https://julialang.org/downloads/#currently_supported_platforms. I don't know if that is something that is worth adding to the image description on docker hub.

**Comment by tianon** [comment]
We have some standard boilerplate docs that get added to any image with an `alpine` variant automatically (https://github.com/docker-library/docs/blob/33f50113e340d5fe24fb678eea38f8e0ad8595ca/.template-helpers/variant-alpine.md), but I definitely agree that something more specific referencing the support tiering is warranted (especially since ARMv7 is Tier 3 also)!

**Comment by tianon** [comment]
Opened a first pass at https://github.com/docker-library/docs/pull/1757 that I'd love to get some eyes on. :smile: :heart: :pray:

**Pull request merged**
