### PR TITLE
Update to 1.3.0 GA

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Looks like `.asc` files are missing on the servers. :disappointed:

**Comment by fredrikekre** [comment]
@ararslan ^

**Comment by ararslan** [comment]
Where are you seeing .asc files missing? They're all there AFAICT.

**Comment by tianon** [comment]
Out Travis builds are getting 404s on https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.0-linux-x86_64.tar.gz.asc -- maybe they just need a restart (I'll give them a kick).

**Comment by tianon** [comment]
Still appears to be getting a 404:

```console
+ curl -fL -o julia.tar.gz.asc https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-1.3.0-linux-x86_64.tar.gz.asc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current[0m
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
```

Are we hitting the wrong URL for the `.asc` files?

**Comment by fredrikekre** [comment]
That curl invocation works for me so it is probably some caching problems?

**Comment by yosifkit** [comment]
Good enough passing of TravisCI. Let's get these built for the Hub.

**Pull request merged**
