### PR TITLE
Add 1.6.0-beta1

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
Ouch, Alpine failing due to linking of some included `7z` binary. :grimacing:

```console
  Installing known registries into `~/.julia`
Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/julia/libexec/7z)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/julia/libexec/7z)
Error relocating /usr/local/julia/libexec/7z: _ZdlPv: symbol not found
Error relocating /usr/local/julia/libexec/7z: _Znam: symbol not found
Error relocating /usr/local/julia/libexec/7z: __cxa_end_catch: symbol not found
Error relocating /usr/local/julia/libexec/7z: __cxa_allocate_exception: symbol not found
Error relocating /usr/local/julia/libexec/7z: __cxa_pure_virtual: symbol not found
Error relocating /usr/local/julia/libexec/7z: _ZdaPv: symbol not found
Error relocating /usr/local/julia/libexec/7z: __gxx_personality_v0: symbol not found
Error relocating /usr/local/julia/libexec/7z: __cxa_begin_catch: symbol not found
Error relocating /usr/local/julia/libexec/7z: __cxa_rethrow: symbol not found
Error relocating /usr/local/julia/libexec/7z: __cxa_throw: symbol not found
Error relocating /usr/local/julia/libexec/7z: _Znwm: symbol not found
Error relocating /usr/local/julia/libexec/7z: _Unwind_Resume: symbol not found
Error relocating /usr/local/julia/libexec/7z: _ZSt9terminatev: symbol not found
Error relocating /usr/local/julia/libexec/7z: __cxa_call_unexpected: symbol not found
Error relocating /usr/local/julia/libexec/7z: __cxa_free_exception: symbol not found
Error relocating /usr/local/julia/libexec/7z: _ZTIPKc: symbol not found
Error relocating /usr/local/julia/libexec/7z: _ZTVN10__cxxabiv116__enum_type_infoE: symbol not found
Error relocating /usr/local/julia/libexec/7z: _ZTIPKw: symbol not found
Error relocating /usr/local/julia/libexec/7z: _ZTIi: symbol not found
Error relocating /usr/local/julia/libexec/7z: _ZTVN10__cxxabiv120__si_class_type_infoE: symbol not found
Error relocating /usr/local/julia/libexec/7z: _ZTVN10__cxxabiv117__class_type_infoE: symbol not found
Error relocating /usr/local/julia/libexec/7z: _ZTVN10__cxxabiv121__vmi_class_type_infoE: symbol not found
ERROR: LoadError: could not download https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/1dad351023a9de247f10061e79f2ef100a481dd9
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:52
  [2] (::Pkg.Types.var"#81#84"{Pkg.Types.Context, String, Pkg.Types.RegistrySpec})(tmp::String)
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:972
  [3] mktempdir(fn::Pkg.Types.var"#81#84"{Pkg.Types.Context, String, Pkg.Types.RegistrySpec}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:729
  [4] mktempdir
    @ ./file.jl:727 [inlined]
  [5] clone_or_cp_registries(ctx::Pkg.Types.Context, regs::Vector{Pkg.Types.RegistrySpec}, depot::String)
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:964
  [6] clone_or_cp_registries
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:957 [inlined]
  [7] clone_default_registries(ctx::Pkg.Types.Context; only_if_empty::Bool)
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:860
  [8] clone_default_registries
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:848 [inlined]
  [9] find_registered!(ctx::Pkg.Types.Context, names::Vector{String}, uuids::Vector{Base.UUID})
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1228
 [10] registry_resolve!(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:754
 [11] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:184
 [12] add
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:148 [inlined]
 [13] add(pkgs::Vector{Pkg.Types.PackageSpec}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:73
 [14] add
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:72 [inlined]
 [15] #add#21
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:70 [inlined]
 [16] add
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:70 [inlined]
 [17] #add#20
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:69 [inlined]
 [18] add(pkg::String)
    @ Pkg.API /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:69
 [19] top-level scope
    @ /tmp/test-dir/julia-downloads/container.jl:10
in expression starting at /tmp/test-dir/julia-downloads/container.jl:10

caused by: failed process: Process(`/usr/local/julia/libexec/7z x /tmp/jl__fbhbai-download.gz -so`, ProcessExited(127)) [127]

Stacktrace:
  [1] pipeline_error
    @ ./process.jl:525 [inlined]
  [2] open(::Pkg.PlatformEngines.var"#24#26"{String}, ::Cmd; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./process.jl:400
  [3] open
    @ ./process.jl:391 [inlined]
  [4] download_verify_unpack(url::String, hash::Nothing, dest::String; tarball_path::Nothing, ignore_existence::Bool, force::Bool, verbose::Bool, quiet_download::Bool)
    @ Pkg.PlatformEngines /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/PlatformEngines.jl:504
  [5] (::Pkg.Types.var"#81#84"{Pkg.Types.Context, String, Pkg.Types.RegistrySpec})(tmp::String)
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:970
  [6] mktempdir(fn::Pkg.Types.var"#81#84"{Pkg.Types.Context, String, Pkg.Types.RegistrySpec}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:729
  [7] mktempdir
    @ ./file.jl:727 [inlined]
  [8] clone_or_cp_registries(ctx::Pkg.Types.Context, regs::Vector{Pkg.Types.RegistrySpec}, depot::String)
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:964
  [9] clone_or_cp_registries
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:957 [inlined]
 [10] clone_default_registries(ctx::Pkg.Types.Context; only_if_empty::Bool)
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:860
 [11] clone_default_registries
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:848 [inlined]
 [12] find_registered!(ctx::Pkg.Types.Context, names::Vector{String}, uuids::Vector{Base.UUID})
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:1228
 [13] registry_resolve!(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Types /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:754
 [14] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:184
 [15] add
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:148 [inlined]
 [16] add(pkgs::Vector{Pkg.Types.PackageSpec}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:73
 [17] add
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:72 [inlined]
 [18] #add#21
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:70 [inlined]
 [19] add
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:70 [inlined]
 [20] #add#20
    @ /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:69 [inlined]
 [21] add(pkg::String)
    @ Pkg.API /buildworker/worker/package_musl64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:69
 [22] top-level scope
    @ /tmp/test-dir/julia-downloads/container.jl:10
```

**Comment by tianon** [comment]
(Just pushed fff19aebd036897d380cd48ba5be847d04e09ec6 which removes Alpine for now so this can move forward while we investigate.)

**Comment by tianon** [comment]
See https://github.com/docker-library/julia/pull/51 for the Alpine continuation.

**Comment by fredrikekre** [comment]
@staticfloat ^

**Pull request merged**
